name = "bixao"
author = "apk modificado"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8658329e9c0812a808b1f85e2a4542c7f042abbcd17dfa59b79c682914eb9cdd"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
