name = "bixao"
author = "apk modificado"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "119d6b541d34034b80b67f66e1471c02cbe60d17a403ec7e4b7c799fdf8d9fa9"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
