name = "bixao"
author = "apk modificado"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5afa63880f30d402a7bef359632c0b3b2c47679e0fb808e919466d3cd4f35706"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
