
[General]
	#The range of the explosion of a coal block.
	#Range: 0.0 ~ 256.0
	explosionRange = 15.0
	#Whether an exploding coal block should cause fire.
	causeFire = true
	#A list of extra configured items that can cause coal to explode
	configuredIgniters = ["minecraft:flint_and_steel", "minecraft:fire_charge"]
	#A list of extra configured blocks that igniters can cause to explode
	configuredBlocks = []

