#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 21 14:53:59 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Just Colored Lighting (0.9.4).zip
enableShaders=false
